### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Arpit980jai** [commonkestrel/GoogleImageScraper#1]
@commonkestrel 
Hello Please Help me with this,
 I have created a blank project and imported the GoogleImageScraper
and copied the below test code
 
 raceback (most recent call last):
  File "C:\Users\acer\pythonProject3\lib\site-packages\GoogleImageScraper\GoogleImageScraper.py", line 42, in urls
    imageObjects = self.get_images(searchData) 
  File "C:\Users\acer\pythonProject3\lib\site-packages\GoogleImageScraper\GoogleImageScraper.py", line 207, in get_images
    imageObjects = pageJson[31][0][12][2]            
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\acer\pythonProject3\lib\site-packages\GoogleImageScraper\GoogleImageScraper.py", line 47, in urls
    imageObjects = self.get_images(searchData)
  File "C:\Users\acer\pythonProject3\lib\site-packages\GoogleImageScraper\GoogleImageScraper.py", line 207, in get_images
    imageObjects = pageJson[31][0][12][2]            
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\acer\PycharmProjects\pythonProject3\main.py", line 5, in <module>
    images = GoogleImageScraper.download(query='dogs', limit=1, arguments={'color':'brown', 'download_format': 'png'})
  File "C:\Users\acer\pythonProject3\lib\site-packages\GoogleImageScraper\__init__.py", line 14, in download
    returnImages = scraper.download(query=query, limit=limit, arguments=arguments)
  File "C:\Users\acer\pythonProject3\lib\site-packages\GoogleImageScraper\GoogleImageScraper.py", line 62, in download
    urls = self.urls(query, arguments=arguments)
  File "C:\Users\acer\pythonProject3\lib\site-packages\GoogleImageScraper\GoogleImageScraper.py", line 49, in urls
    raise UnpackError('Failed to fetch image objects.')
GoogleImageScraper.errors.UnpackError: Failed to fetch image objects.

Process finished with exit code 1

![image](https://user-images.githubusercontent.com/56965707/236006563-5f66ca47-5035-49c9-9994-7846f7b069d3.png)

Please take a look at it

**Comment by Arpit980jai** [comment]
STILL wAITING FOR your response
